feat: go test and coverage
zeabix-cloud-native/go-coverage-test-quality-gate-orb pull request #1
Opened 2023-01-16 14:49 UTC by amornc

About this orb

- This orb will run go test with covermode atomic then check quality gate from output.
- Input parameter testcoverage_threshold to specific the coverage percentage.
- save result to artifacts

2023-01-17 02:43 UTC, puizeabix requested changes
I've put some comments, please have a look

2023-01-17 02:43 UTC, puizeabix commented on src/commands/go-test.yml
> +    description: "the coverage percentage"
incorrect description

2023-01-17 02:43 UTC, puizeabix commented on pkg/db/db.go
> +package db
Please remove all of snocko code from this repo krub

2023-01-17 02:43 UTC, puizeabix commented on coverage.py
> +import re;
Are we using this? or using the logic in the scripts/ folder. Seems to do the same thing, please remove if it's not used

2023-01-17 06:32 UTC, amornc commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/zeabix-cloud-native/go-coverage-test-quality-gate?version=dev:7efeddb88b78b4d680e229eafa2d5cda35984467

2023-01-17 06:33 UTC, amornc commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/zeabix-cloud-native/go-coverage-test-quality-gate?version=dev:1bf2195d1b5040f9497d0d0ce2bb5ceff396ef0c

2023-01-17 06:36 UTC, amornc commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/zeabix-cloud-native/go-coverage-test-quality-gate?version=dev:14976d2a698e7bb58869e5f28fe1e873f433ece0

2023-01-17 06:43 UTC, amornc commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/zeabix-cloud-native/go-coverage-test-quality-gate?version=dev:4ed2968565e78719655e115f851df6b33a8aa2eb

2023-01-17 06:45 UTC, amornc commented on src/commands/go-test.yml
> +    description: "the coverage percentage"
Done krub.

2023-01-17 06:46 UTC, amornc commented on pkg/db/db.go
> +package db
Done krub.

2023-01-17 06:47 UTC, amornc commented on coverage.py
> +import re;
Already change the code to the new sample application krub.

2023-01-18 01:25 UTC, merged

2023-01-18 01:26 UTC, amornc commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/zeabix-cloud-native/go-coverage-test-quality-gate?version=dev:a457432158acc4e2da28285ffea21c7163f17275

2023-01-18 02:41 UTC, amornc commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/zeabix-cloud-native/go-coverage-test-quality-gate?version=dev:a457432158acc4e2da28285ffea21c7163f17275